---
#Блоки и условие when#
- name: My primer
  hosts: all
  become: yes

  vars:
    soucse_file: ./MyWebSite/Index.html
    destin_file: /var/www/html
  
  tasks:
  - name: Chek and Print OS family
    debag: var=ansible_os_family

  - block: #======Block for Ubuntu======
    
    - name: Install Apache for servers
      apt: name=apache2 state=latest

    - name: Copy file for servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache for Ubuntu

    - name: Start Apache on servers
      service: name=apache2 state=started enabled=yes
    
    when: ansible_os_family == "Debian"
  
  - block: #=====Block for RedHat=====

    - name: Install Apache for RedHat
      yam: name=httpd state=latest

    - name: Copy file for servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache for  RedHat

    - name: Start Apache
      service: name=httpd state=started enabled=yes
      
    when: ansible_os_family == "RedHat"

  handlers:
  - name: Restart Apache for RedHat
    service: name=httpd state=restarted
  
  - name: Restart Apache for Ubuntu
    service: name=apache2 state=restarted
